# Generated by Django 3.0.6 on 2020-05-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_Name',
            new_name='name',
        ),
    ]
